baseURL = 'https://emm218.github.io/'
languageCode = 'en-us'
title = "Emmy Alme"
uglyurls = true
enableGitInfo = true
disableKinds = ['taxonomy', 'term', 'section']

markup.highlight.noClasses = false
markup.goldmark.renderer.unsafe = true
markup.tableOfContents.ordered = true

[outputFormats.rss]
    baseName = 'feed'

[params]
    description = "A home for my projects"
    mainsections = ["projects", "posts"]

[[menu.main]]
    name = "Github"
    url = "https://github.com/emm218"
    [menu.main.params]
        rel = "me"

[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/emmaline-alme/"
    [menu.main.params]
        rel = "me"

[[menu.main]]
    name = "PGP key"
    url = "pgp.txt"
