baseURL = 'https://emm218.github.io/'
languageCode = 'en-us'
title = "Emmy Alme"
uglyurls = true
enableGitInfo = true
disableKinds = ['taxonomy', 'term', 'section']

markup.highlight.noClasses=false

[params]
    description = "A home for my projects"

[[menu.main]]
    name = "github"
    url = "https://github.com/emm218"
    [menu.main.params]
        rel = "me"

[[menu.main]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/emmaline-alme/"
    [menu.main.params]
        rel = "me"

[[menu.main]]
    name = "pgp key"
    url = "pgp.txt"
